<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AppSetting extends Model
{
    protected $fillable = [
        'brand_name',
        'primary_color',
        'logo_url',
        'support_email',
        'support_phone',
        'support_address',
        'notifications_push_enabled',
        'notifications_in_app_enabled',
        'notifications_email_fallback_enabled',
        'meeting_reminder_enabled',
        'notifications_dedupe_seconds',
        'meeting_reminder_minutes_before',
        'task_item_progress_reminder_enabled',
        'task_item_progress_reminder_time',
        'task_item_update_submission_notification_enabled',
        'task_item_update_feedback_notification_enabled',
        'lead_capture_notification_enabled',
        'contract_unpaid_reminder_enabled',
        'contract_unpaid_reminder_time',
        'contract_expiry_reminder_enabled',
        'contract_expiry_reminder_time',
        'contract_expiry_reminder_days_before',
        'project_handover_min_progress_percent',
        'smtp_custom_enabled',
        'smtp_mailer',
        'smtp_host',
        'smtp_port',
        'smtp_encryption',
        'smtp_username',
        'smtp_password',
        'smtp_from_address',
        'smtp_from_name',
        'chatbot_enabled',
        'chatbot_provider',
        'chatbot_model',
        'chatbot_api_key',
        'chatbot_system_message_markdown',
        'chatbot_history_pairs',
        'gsc_enabled',
        'gsc_client_id',
        'gsc_client_secret',
        'gsc_refresh_token',
        'gsc_access_token',
        'gsc_access_token_expires_at',
        'gsc_row_limit',
        'gsc_data_state',
        'gsc_alert_threshold_percent',
        'gsc_recipes_path_token',
        'gsc_brand_terms',
        'gsc_sync_time',
        'updated_by',
    ];

    protected $casts = [
        'notifications_push_enabled' => 'boolean',
        'notifications_in_app_enabled' => 'boolean',
        'notifications_email_fallback_enabled' => 'boolean',
        'meeting_reminder_enabled' => 'boolean',
        'notifications_dedupe_seconds' => 'integer',
        'meeting_reminder_minutes_before' => 'integer',
        'task_item_progress_reminder_enabled' => 'boolean',
        'task_item_progress_reminder_time' => 'string',
        'task_item_update_submission_notification_enabled' => 'boolean',
        'task_item_update_feedback_notification_enabled' => 'boolean',
        'lead_capture_notification_enabled' => 'boolean',
        'contract_unpaid_reminder_enabled' => 'boolean',
        'contract_expiry_reminder_enabled' => 'boolean',
        'contract_expiry_reminder_days_before' => 'integer',
        'project_handover_min_progress_percent' => 'integer',
        'smtp_custom_enabled' => 'boolean',
        'smtp_port' => 'integer',
        'chatbot_enabled' => 'boolean',
        'chatbot_history_pairs' => 'integer',
        'gsc_enabled' => 'boolean',
        'gsc_access_token_expires_at' => 'datetime',
        'gsc_row_limit' => 'integer',
        'gsc_alert_threshold_percent' => 'integer',
        'gsc_brand_terms' => 'array',
    ];

    public static function defaults(): array
    {
        return [
            'brand_name' => config('app.name', 'Jobs ClickOn'),
            'primary_color' => '#04BC5C',
            'logo_url' => '/brand/icon.png',
            'support_email' => null,
            'support_phone' => null,
            'support_address' => null,
            'notifications_push_enabled' => true,
            'notifications_in_app_enabled' => true,
            'notifications_email_fallback_enabled' => true,
            'meeting_reminder_enabled' => true,
            'notifications_dedupe_seconds' => 45,
            'meeting_reminder_minutes_before' => 60,
            'task_item_progress_reminder_enabled' => true,
            'task_item_progress_reminder_time' => '09:00',
            'task_item_update_submission_notification_enabled' => true,
            'task_item_update_feedback_notification_enabled' => true,
            'lead_capture_notification_enabled' => true,
            'contract_unpaid_reminder_enabled' => true,
            'contract_unpaid_reminder_time' => '08:00',
            'contract_expiry_reminder_enabled' => true,
            'contract_expiry_reminder_time' => '09:00',
            'contract_expiry_reminder_days_before' => 3,
            'project_handover_min_progress_percent' => 90,
            'smtp_custom_enabled' => false,
            'smtp_mailer' => 'smtp',
            'smtp_host' => null,
            'smtp_port' => 587,
            'smtp_encryption' => 'tls',
            'smtp_username' => null,
            'smtp_password' => null,
            'smtp_from_address' => null,
            'smtp_from_name' => null,
            'chatbot_enabled' => false,
            'chatbot_provider' => 'gemini',
            'chatbot_model' => 'gemini-2.0-flash',
            'chatbot_api_key' => null,
            'chatbot_system_message_markdown' => null,
            'chatbot_history_pairs' => 8,
            'gsc_enabled' => false,
            'gsc_client_id' => null,
            'gsc_client_secret' => null,
            'gsc_refresh_token' => null,
            'gsc_access_token' => null,
            'gsc_access_token_expires_at' => null,
            'gsc_row_limit' => 2500,
            'gsc_data_state' => 'all',
            'gsc_alert_threshold_percent' => 30,
            'gsc_recipes_path_token' => '/recipes',
            'gsc_brand_terms' => [],
            'gsc_sync_time' => '11:17',
        ];
    }
}
